import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Bell, ChevronDown, CircleHelp, Clock3, Download, Flame, LayoutDashboard, Menu, Search, Settings, ShieldAlert, Sparkles, Target, TrendingUp, WalletCards } from 'lucide-react';
import './styles.css';

const coins = [
  { name:'Aster', ticker:'ASTER', price:'$0.7184', change:'+8.42%', score:87, pattern:'W Bottom', volume:'3.8×', news:'Mainnet upgrade • 6h ago', days:'2–4 days', status:'Strong setup', color:'#7967ff' },
  { name:'Hyperliquid', ticker:'HYPE', price:'$31.92', change:'+5.18%', score:81, pattern:'Bull Flag', volume:'2.6×', news:'Open interest rising • 3h ago', days:'1–3 days', status:'Watch closely', color:'#42d7a1' },
  { name:'Pyth Network', ticker:'PYTH', price:'$0.1216', change:'+4.90%', score:78, pattern:'Hammer', volume:'2.1×', news:'New integration • 10h ago', days:'3–6 days', status:'Building', color:'#e88af7' },
  { name:'Celestia', ticker:'TIA', price:'$1.486', change:'+3.21%', score:74, pattern:'Doji reversal', volume:'1.8×', news:'Token unlock monitored', days:'4–7 days', status:'Early signal', color:'#6ea9ff' },
  { name:'Ethena', ticker:'ENA', price:'$0.2851', change:'+2.68%', score:72, pattern:'Double bottom', volume:'1.6×', news:'Protocol metrics positive', days:'5–8 days', status:'Early signal', color:'#e7b050' },
];

function MiniChart({ color, active }) { return <svg className="mini-chart" viewBox="0 0 180 56" preserveAspectRatio="none"><defs><linearGradient id={'g'+color.slice(1)} x1="0" x2="0" y1="0" y2="1"><stop stopColor={color} stopOpacity=".28"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient></defs><path d={active?'M0 43 C10 45, 12 30, 24 35 S42 47, 51 39 S65 14, 78 23 S93 42, 105 34 S118 19, 130 25 S142 34, 151 18 S166 9, 180 7 L180 56 L0 56Z':'M0 39 C12 26, 20 45, 32 31 S48 38, 59 25 S70 44, 86 36 S101 17, 113 29 S131 21, 145 32 S161 23, 180 10 L180 56 L0 56Z'} fill={'url(#g'+color.slice(1)+')'}/><path d={active?'M0 43 C10 45, 12 30, 24 35 S42 47, 51 39 S65 14, 78 23 S93 42, 105 34 S118 19, 130 25 S142 34, 151 18 S166 9, 180 7':'M0 39 C12 26, 20 45, 32 31 S48 38, 59 25 S70 44, 86 36 S101 17, 113 29 S131 21, 145 32 S161 23, 180 10'} fill="none" stroke={color} strokeWidth="2.3"/></svg> }

function App(){
 const [tab,setTab]=useState('Signals'); const [query,setQuery]=useState(''); const [range,setRange]=useState('24H');
 const filtered=useMemo(()=>coins.filter(c=>(c.name+c.ticker+c.pattern).toLowerCase().includes(query.toLowerCase())),[query]);
 return <div className="app">
  <aside><div className="brand"><span className="brand-mark">R</span><span>radar<span>loop</span></span></div><nav>{[[LayoutDashboard,'Overview'],[Sparkles,'Signals'],[Activity,'Market scanner'],[WalletCards,'Portfolio'],[Bell,'Alerts']].map(([I,n])=><button className={tab===n|| (tab==='Signals'&&n==='Signals')?'nav-active':''} onClick={()=>setTab(n)} key={n}><I size={19}/>{n}</button>)}</nav><div className="side-bottom"><button><Settings size={19}/>Settings</button><div className="pro-card"><div className="tiny-label">RADAR PRO</div><strong>Research with clarity.</strong><p>Signals, news & risk in one view.</p><button className="upgrade">Explore Pro <span>→</span></button></div><div className="profile"><div className="avatar">SK</div><div><b>Suresh Kumar</b><small>Free plan</small></div><ChevronDown size={16}/></div></div></aside>
  <main><header><button className="mobile-menu"><Menu/></button><div className="crumb">Market scanner <span>/</span> <b>Futures signals</b></div><div className="header-actions"><button className="help"><CircleHelp size={19}/> How it works</button><button className="icon"><Bell size={19}/><i/></button><button className="connect">Connect exchange</button></div></header>
   <section className="hero"><div><div className="eyebrow"><span/> LIVE FUTURES RESEARCH</div><h1>Find momentum <em>before</em> it moves.</h1><p>USD-M futures signals based on market structure, volume, news and on-chain activity — not predictions.</p></div><div className="risk"><ShieldAlert size={19}/><div><b>Risk-first research</b><span>No signal guarantees a price move. Always verify and manage risk.</span></div></div></section>
   <section className="controls"><div className="search"><Search size={18}/><input placeholder="Search coins, patterns..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filters">{['24H','7D','30D'].map(x=><button className={range===x?'selected':''} onClick={()=>setRange(x)} key={x}>{x}</button>)}<button className="filter"><Target size={16}/> Filters <span>3</span></button></div></section>
   <section className="stats"><div><span className="stat-icon violet"><Sparkles size={19}/></span><p>Qualified signals</p><strong>24</strong><small>↑ 6 since yesterday</small></div><div><span className="stat-icon green"><TrendingUp size={19}/></span><p>Avg. signal score</p><strong>76<span>/100</span></strong><small>Across 412 markets</small></div><div><span className="stat-icon orange"><Flame size={19}/></span><p>Volume anomalies</p><strong>18</strong><small>Above 2× daily average</small></div><div><span className="stat-icon blue"><Clock3 size={19}/></span><p>Latest scan</p><strong>2m</strong><small>Updated continuously</small></div></section>
   <section className="section-title"><div><h2>High-conviction setups</h2><p>Signals passing your current quality filters.</p></div><button className="outline">View all signals <span>→</span></button></section>
   <section className="table"><div className="thead"><span>ASSET</span><span>PRICE / 24H</span><span>STRUCTURE</span><span>CONFIRMATION</span><span>CATALYST</span><span>WINDOW</span><span>SCORE</span></div>{filtered.map((c,i)=><article className="coin" key={c.ticker}><div className="asset"><div className="coin-icon" style={{background:c.color}}>{c.ticker[0]}</div><div><b>{c.name}</b><small>{c.ticker} · USD-M Perp</small></div></div><div><b>{c.price}</b><small className="up">{c.change}</small></div><div><span className="pattern">{c.pattern}</span><MiniChart color={c.color} active={i===0}/></div><div><b className="volume">{c.volume}</b><small>relative volume</small></div><div><span className="news-dot"/><small>{c.news}</small></div><div><b>{c.days}</b><small>research window</small></div><div className="score"><span style={{'--score':c.score}}>{c.score}</span><small>{c.status}</small></div></article>)}</section>
   <div className="disclaimer"><ShieldAlert size={16}/><span><b>Research, not financial advice.</b> Radarloop surfaces measurable conditions; it cannot determine or guarantee future price direction. Futures trading carries substantial risk.</span></div>
  </main>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
